### ISSUE TITLE
Add a pull request check using `GitHub Action`

### ISSUE THREAD

**Issue by ddanilovich-demo** [ddanilovich-demo/ng-demo#6]
### Details

Add a workflow file `.github/workflows/check-pr.yml`

```yaml
name: Check PR

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 20
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier check
        run: npm run prettier:check
      - name: Run ESLint check
        run: npm run eslint:check
      - name: Run tests
        run: npm test
```

Protect the `main` branch from the direct push and by `GitHub Actions` checks (`Settings > Branches`).

### References

- [GitHub Actions docs](https://docs.github.com/en/actions)
- [GitHub Actions Marketplace](https://github.com/marketplace?type=actions)
