### ISSUE TITLE
Integrate `Dependabot`

### ISSUE THREAD

**Issue by ddanilovich-demo** [ddanilovich-demo/ng-demo#8]
### Details

Add a `Dependabot` config file `.github/workflows/check-pr.yml` with content:

```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
      time: '22:00'
    open-pull-requests-limit: 20
    versioning-strategy: increase
    assignees:
      - 'ddanilovich-demo'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '22:00'
    open-pull-requests-limit: 20
    assignees:
      - 'ddanilovich-demo'
```

Downgrade some dependencies.

### References

- [GitHub Dependabot docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates)
