### ISSUE TITLE
Integrate `semantic-release`

### ISSUE THREAD

**Issue by ddanilovich-demo** [ddanilovich-demo/ng-demo#9]
### Details

Add `GitHub Action` workflow with steps:

- perform checks
- build
- deploy to `Github Pages`
- create semantic release

Install dependencies

```shell
 npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git
```

Add `npm script`

```json
{
  "build:gh-pages": "ng build --baseHref=\"/ng-demo/\""
}
```

Add `release.config.js`

```javascript
module.exports = {
  branches: ['main'],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    [
      '@semantic-release/changelog',
      {
        changelogTitle: '# Changelog',
        changelogFile: 'CHANGELOG.md',
      },
    ],
    '@semantic-release/github',
    [
      '@semantic-release/git',
      {
        assets: ['CHANGELOG.md'],
        message: 'chore: update `CHANGELOG.md` [skip ci]',
      },
    ],
  ],
};
```

Change  the`version` field in the `package.json` file to `0.0.0-development`

Add a workflow file `.github/workflows/release.yml`

```yaml
name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 20
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier check
        run: npm run prettier:check
      - name: Run ESLint check
        run: npm run eslint:check
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
      - name: Release
        run: npm run release
```

### References

- [semantic-release docs](https://semantic-release.gitbook.io/semantic-release/)
